### ISSUE TITLE
[DOOR-42] DOS-Trigger Jenkins run - java.io exceptions in the end of scan phase

### ISSUE THREAD

**Issue by Etsija** [doubleopen-project/dos#606]
The full scan log is shown here:

[http://5.9.139.61:8080/job/ORT/100/execution/node/201/log/?consoleFull](http://5.9.139.61:8080/job/ORT/100/execution/node/201/log/?consoleFull)

An example of the exception:

`09:01:56.682 [pool-47-thread-5] WARN  org.eclipse.jgit.internal.storage.file.PackDirectory - Pack file /tmp/ort-DefaultWorkingTreeCache15753860875126209126/.git/objects/pack/pack-66400b936b07f2a949aec563a546ed9252ff161e.pack is corrupt, removing it from pack list
org.eclipse.jgit.errors.PackInvalidException: Pack file invalid: /tmp/ort-DefaultWorkingTreeCache15753860875126209126/.git/objects/pack/pack-66400b936b07f2a949aec563a546ed9252ff161e.pack
	at org.eclipse.jgit.internal.storage.file.Pack.idx(Pack.java:172)
	at org.eclipse.jgit.internal.storage.file.Pack.get(Pack.java:288)
	at org.eclipse.jgit.internal.storage.file.PackDirectory.open(PackDirectory.java:225)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openPackedObject(ObjectDirectory.java:412)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openPackedFromSelfOrAlternate(ObjectDirectory.java:375)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openObjectWithoutRestoring(ObjectDirectory.java:365)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openObject(ObjectDirectory.java:350)
	at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:133)
	at org.eclipse.jgit.lib.ObjectReader.open(ObjectReader.java:216)
	at org.eclipse.jgit.internal.storage.pack.PackWriter.buffer(PackWriter.java:1998)
	at org.eclipse.jgit.internal.storage.pack.DeltaWindow.buffer(DeltaWindow.java:377)
	at org.eclipse.jgit.internal.storage.pack.DeltaWindow.delta(DeltaWindow.java:264)
	at org.eclipse.jgit.internal.storage.pack.DeltaWindow.searchInWindow(DeltaWindow.java:188)
	at org.eclipse.jgit.internal.storage.pack.DeltaWindow.search(DeltaWindow.java:144)
	at org.eclipse.jgit.internal.storage.pack.DeltaTask.runWindow(DeltaTask.java:294)
	at org.eclipse.jgit.internal.storage.pack.DeltaTask.call(DeltaTask.java:269)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.io.IOException: Unreadable pack index: /tmp/ort-DefaultWorkingTreeCache15753860875126209126/.git/objects/pack/pack-66400b936b07f2a949aec563a546ed9252ff161e.idx
	at org.eclipse.jgit.internal.storage.file.PackIndex.open(PackIndex.java:69)
	at org.eclipse.jgit.internal.storage.file.Pack.idx(Pack.java:177)
	... 19 common frames omitted
Caused by: java.io.FileNotFoundException: /tmp/ort-DefaultWorkingTreeCache15753860875126209126/.git/objects/pack/pack-66400b936b07f2a949aec563a546ed9252ff161e.idx (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at org.eclipse.jgit.util.io.SilentFileInputStream.<init>(SilentFileInputStream.java:31)
	at org.eclipse.jgit.internal.storage.file.PackIndex.open(PackIndex.java:65)
	... 20 common frames omitted`

<sub>From [SyncLinear.com](https://synclinear.com) | [DOOR-42](https://linear.app/double-open/issue/DOOR-42/dos-trigger-jenkins-run-javaio-exceptions-in-the-end-of-scan-phase)</sub>

**Comment by Etsija** [comment]
This hasn't happened since, and the reason for it wasn't found, so let's close it for now, and reopen if necessary.
